apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mycharts.fullname" . }}-custom-dns-config
  labels:
  {{- include "mycharts.labels" . | nindent 4 }}
data:
  grafana.local: {{ .Values.customDnsConfig.grafanaLocal | quote }}
  prometheus.local: {{ .Values.customDnsConfig.prometheusLocal | quote }}
  victoriametrics.local: {{ .Values.customDnsConfig.victoriametricsLocal | quote
    }}