apiVersion: v1
kind: Service
metadata:
  name: {{ include "mycharts.fullname" . }}-grafana-service
  labels:
  {{- include "mycharts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.grafanaService.type }}
  selector:
    app: grafana
  {{- include "mycharts.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.grafanaService.ports | toYaml | nindent 2 -}}