apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mycharts.fullname" . }}-grafana-provisioning-datasources
  labels:
  {{- include "mycharts.labels" . | nindent 4 }}
data:
  datasources.yml: {{ .Values.grafanaProvisioningDatasources.datasourcesYml | toYaml
    | indent 1 }}