apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mycharts.fullname" . }}-nginx-config
  labels:
  {{- include "mycharts.labels" . | nindent 4 }}
data:
  nginx.conf: {{ .Values.nginxConfig.nginxConf | toYaml | indent 1 }}