apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mycharts.fullname" . }}-prometheus-config
  labels:
  {{- include "mycharts.labels" . | nindent 4 }}
binaryData: {}
data:
  prometheus.yml: {{ .Values.prometheusConfig.prometheusYml | toYaml | indent 1 }}