apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mycharts.fullname" . }}-prometheus-data
  labels:
  {{- include "mycharts.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.prometheusData.storageRequest | quote }}