apiVersion: v1
kind: Service
metadata:
  name: {{ include "mycharts.fullname" . }}-prometheus-service
  labels:
  {{- include "mycharts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheusService.type }}
  selector:
    app: prometheus
  {{- include "mycharts.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.prometheusService.ports | toYaml | nindent 2 -}}