apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mycharts.fullname" . }}-config
  labels:
  {{- include "mycharts.labels" . | nindent 4 }}
data:
  victoriametrics.yaml: {{ .Values.config.victoriametricsYaml | toYaml | indent 1
    }}