apiVersion: v1
kind: Service
metadata:
  name: {{ include "mycharts.fullname" . }}-service
  labels:
  {{- include "mycharts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: victoriametrics
  {{- include "mycharts.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}